# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "bot" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Build Go binary
      run: |
        go mod tidy
        export CGO_ENABLED=0
        export GOOS=linux 
        export GOARCH=amd64
        go build -o bot ./bot && go build -o vb-api ./api
        echo "Build completed."

    - name: Copy API binary to VPS
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "vb-bot, vb-api"
        target: "/etc/verbosebasson"

    - name: Restart service on VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          sudo systemctl stop vbd || true
          sudo systemctl stop vb_api || true
          chmod +x /etc/verbosebasson/bot
          chmod +x /etc/verbosebasson/vb-api
          sudo systemctl start vbd
          sudo systemctl start vb_api
